### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mpkuse** [chrischoy/OSGRenderer#7]
I have successfully installed OpenSceneGraph. However, I am a bit new to python and do not get what is anaconda. I have installing python packages with pip. 

Can you help me please on installing your Renderer

**Comment by chrischoy** [comment]
You can use system python. Install the python dev package from apt-get and numpy using pip

```
sudo apt-get install python2.7-dev
pip install numpy
```

Then, you would be able to find pyconfig.h from either

```
/usr/include/python2.7/pyconfig.h
/usr/local/include/python2.7/pyconfig.h
/usr/include/x86_64-linux-gnu/python2.7/pyconfig.h
```

To find the numpy header, please refer to http://stackoverflow.com/questions/14375222/find-python-header-path-from-within-python

**Comment by mpkuse** [comment]
I sorted out this issue by editing the Makefile and setting the NUMPY_INCLUDE and PYCONFIG_PATH correctly. Compilation worked. 

I tried your demo.py and it works too and I get displays of the car as on your readme on github. 

However, when try to import Renderer in python in my program it does not work.
>>> from PyRenderer import Renderer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named PyRenderer

I know this has to do with the path not set. I am a noob in python can you please help me on this.
Thanks!

**Comment by chrischoy** [comment]
To import the package, you need to add it to the search path. Add the path to PyRenderer.so to your PYTHONPATH.

http://stackoverflow.com/questions/19917492/how-to-use-pythonpath
